version: "3.8"
services:
  dev:
    build:
      context: ./app
      dockerfile: ./dev.Dockerfile
      target: dev
    volumes:
      - .:/
    command: npm run dev
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
  prod:
    build:
      context: ./app
      dockerfile: ./Dockerfile
      target: prod
    volumes:
      - .:/
    command: npm start
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
